import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from scipy.stats import randint

# Load dataset
data = pd.read_excel(r"C:\Users\tarun\OneDrive\Desktop\data.xlsx", engine="openpyxl")

# Drop rows with missing values
data = data.dropna()

# Convert timestamp to datetime format
data['timestamp'] = pd.to_datetime(data['timestamp'])

# Extract time-based features
data['hour'] = data['timestamp'].dt.hour
data['day'] = data['timestamp'].dt.day
data['month'] = data['timestamp'].dt.month
data['year'] = data['timestamp'].dt.year

# Create lag features for better predictions
data['prev_demand'] = data['electricity_demand'].shift(1)
data['rolling_avg'] = data['electricity_demand'].rolling(window=3).mean()

# Fill NaN values generated by shift and rolling
data = data.fillna(method='bfill')

# Drop timestamp column
data = data.drop(columns=['timestamp'])

# Define features and target
X = data.drop(columns=['electricity_demand'])  # Features
y = data['electricity_demand']  # Target variable

# Split dataset into training, validation, and testing sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2, random_state=42)
X_dev, X_test, y_dev, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Hyperparameter tuning using RandomizedSearchCV
param_dist = {
    'n_estimators': randint(100, 500),
    'max_depth': [10, 20, 30, None],
    'min_samples_split': randint(2, 20),
    'min_samples_leaf': randint(1, 10),
    'max_features': ['auto', 'sqrt', 'log2'],
    'bootstrap': [True, False]
}

rf = RandomForestRegressor(random_state=42)
random_search = RandomizedSearchCV(estimator=rf, param_distributions=param_dist, n_iter=20, cv=3, n_jobs=-1, verbose=2, random_state=42)
random_search.fit(X_train, y_train)

# Best model
best_model = random_search.best_estimator_
# print(/"best parameter using hypertuning :- ",random_search.best_estimator_)

# Save the trained model
model_path = r"C:\Users\tarun\OneDrive\Desktop\best_model.pkl"
joblib.dump(best_model, model_path)
print(f"Model saved at {model_path}")

# Load the saved model
best_model = joblib.load(model_path)
print("Model loaded successfully.")

# Make predictions
y_train_pred = best_model.predict(X_train)
y_dev_pred = best_model.predict(X_dev)
y_test_pred = best_model.predict(X_test)

# Evaluate model
def evaluate_model(y_true, y_pred, dataset_name):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    accuracy = r2 * 100  # Assuming R^2 score as a percentage accuracy
    print(f'{dataset_name} Set Evaluation:')
    print(f'MAE: {mae}')
    print(f'MSE: {mse}')
    print(f'RMSE: {rmse}')
    print(f'R^2 Score: {r2}')
    print(f'Accuracy: {accuracy}%')
    print('-' * 40)

# Print evaluation results
evaluate_model(y_train, y_train_pred, "Train")
evaluate_model(y_dev, y_dev_pred, "Dev")
evaluate_model(y_test, y_test_pred, "Test")